services:
  vllm-server:
    image: vllm/vllm-openai:latest
    shm_size: '32g'
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ['0,1,2,3,4,5,6,7']
    ipc: host
    command: >
      --model ${MODEL:-Infermatic/Llama-3.3-70B-Instruct-FP8-Dynamic}
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size ${TENSOR_PARALLEL_SIZE:-2}
      --pipeline-parallel-size ${PIPELINE_PARALLEL_SIZE:-1}
      --max-model-len ${MAX_MODEL_LEN:-8000}
      --gpu-memory-utilization 0.95
      --disable-log-requests
      --trust-remote-code
      --max-num-seqs ${MAX_NUM_SEQS:-128}
      --max-num-batched-tokens ${MAX_NUM_BATCHED_TOKENS:-32768}
      --enable-prefix-caching
      --enable-chunked-prefill
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      # - VLLM_USE_V1=1
      - VLLM_WORKER_MULTIPROC_METHOD=spawn
    env_file:
      - ./.env